In [2]:
# 연습문제

# 01. 0 ~ 11 정수를 채운 (3, 4) 넘파이 배열 생성
import numpy as np
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
# 02
import numpy as np
list1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
a = np.array(list1)
b = a[0:2, 0:2]
print(b)
c = a[1:, 1:]
print(c)


[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


In [4]:
# 03
import numpy as np
arr = np.array([[[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9],
                 [10, 11, 12]]])

print(arr.shape)

(1, 4, 3)


In [5]:
# 04
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = a.reshape(-1) # 유연 / 원본 영향이 미침
c = a.ravel() # 성능 / 원본 영향이 미침
d = a.flatten() # 독립된 배열

a[0][0] = 0

print(b)
print(c)
print(d)

[0 2 3 4 5 6]
[0 2 3 4 5 6]
[1 2 3 4 5 6]


In [6]:
# 05
import numpy as np

a = np.arange(8)
a.shape = (4, 2)
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [19]:
# 06
import pandas as pd

data = {
    "이름": ["허준호", "이가원", "배규민", "고고림", "이새봄", "이보람", "이루리", "오다현"],
    "성별": ["남자", "여자", "남자", "남자", "여자", "여자", "여자", "여자"],
    "나이": [30, 24, 23, 21, 28, 26, 24, 24],
    "키": [183, 162, 179, 182, 160, 163, 157, 172]
}

df = pd.DataFrame(data)

df = df.astype({'나이': 'str',
                '키': 'str'})

print(df)
df[(df['나이'] > '24') & (df['성별'] == '여자')]

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172


이름  성별  나이    키
4  이새봄  여자  28  160
5  이보람  여자  26  163

In [20]:
# 07
df.describe()

이름  성별  나이    키
count     8   8   8    8
unique    8   2   6    8
top     허준호  여자  24  183
freq      1   5   3    1

In [21]:
# 08
df.set_index('이름', inplace=True)
df

성별  나이    키
이름              
허준호  남자  30  183
이가원  여자  24  162
배규민  남자  23  179
고고림  남자  21  182
이새봄  여자  28  160
이보람  여자  26  163
이루리  여자  24  157
오다현  여자  24  172

In [28]:
# 09
import numpy as np

list1 = [
    [1,2],
    [3,4]
]

arr = np.array(list1)
print(arr)
bool_index = (arr % 2 == 0)
print(bool_index) # 마스킹

print('짝수\n', arr[bool_index])

res = arr[arr % 2 == 1]
print('홀수\n',res)

[[1 2]
 [3 4]]
[[False  True]
 [False  True]]
짝수
 [2 4]
홀수
 [1 3]


In [31]:
# 10
arr1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

arr2 = arr1.copy()
print('arr1\n', arr1)
print('arr2\n', arr2)

arr1[0,0] = 10
print('='*10)
print("변경 후 -> arr1\n", arr1)
print("변경 후 -> arr2\n", arr2)

arr1
 [[1 2 3 4]
 [5 6 7 8]]
arr2
 [[1 2 3 4]
 [5 6 7 8]]
변경 후 -> arr1
 [[10  2  3  4]
 [ 5  6  7  8]]
변경 후 -> arr2
 [[1 2 3 4]
 [5 6 7 8]]
