### **1. 넘파이 배열 생성**

In [2]:
#코드 6-1
import numpy as np

#리스트를 생성하고 배열로 변환하기
list1 = [1, 2, 3, 4]
a = np.array(list1)
print('a.shape: ', a.shape)
print('a[0]: ', a[0])

a.shape:  (4,)
a[0]:  1


In [2]:
#2차원 배열 생성하기
b = np.array([[1, 2, 3], [4, 5, 6]])
print('b.shape: ', b.shape)
print('b[0,0]: ', b[0,0])
print('b[0]: ', b[0])

b.shape:  (2, 3)
b[0,0]:  1
b[0]:  [1 2 3]


In [3]:
# 1. array() - 리스트를 배열로 변환
a = np.array([1, 2, 3])
print("array:", a)

# 2. arange() - 일정한 간격의 수를 ndarray 배열로
b = np.arange(0, 10, 2)  # 0부터 10 미만까지 2 간격
print("arange:", b)

# 3. ones() - 1로 채운 배열 생성
c = np.ones((2, 3))  # 2행 3열
print("ones:\n", c)

# 4. zeros() - 0으로 채운 배열 생성
d = np.zeros((3, 2))  # 3행 2열
print("zeros:\n", d)

# 5. empty() - 초기화되지 않은 빈 배열 생성
e = np.empty((2, 2))  # 값이 초기화되지 않음 (랜덤값)
print("empty:\n", e)

# 6. eye() 또는 identity() - 단위 행렬 생성
f = np.eye(3)  # 3x3 단위 행렬
print("eye:\n", f)

g = np.identity(3)  # 3x3 단위 행렬
print("identity:\n", g)

# 7. linspace() - 지정한 구간을 균일하게 나눈 값 생성
h = np.linspace(0, 1, 5)  # 0부터 1까지 5개의 균등한 값
print("linspace:", h)

# 8. full() - 지정한 값으로 채운 배열 생성
i = np.full((2, 3), 7)  # 2행 3열 배열을 7로 채움
print("full:\n", i)

array: [1 2 3]
arange: [0 2 4 6 8]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
zeros:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
empty:
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
linspace: [0.   0.25 0.5  0.75 1.  ]
full:
 [[7 7 7]
 [7 7 7]]


In [4]:
#코드 6-2
a = np.zeros(2)
print('a\n', a)
b = np.zeros((2,2))
print('b\n', b)
c = np.ones((2,3))
print('c\n', c)
d = np.full((2,3), 5)
print('d\n', d)
e = np.eye(3)
print('e\n', e)

a
 [0. 0.]
b
 [[0. 0.]
 [0. 0.]]
c
 [[1. 1. 1.]
 [1. 1. 1.]]
d
 [[5 5 5]
 [5 5 5]]
e
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
#코드 6-3
#실수형 배열 생성하기
a = np.array([1, 2], dtype=np.float64)
print(a.dtype)

#정수형 배열로 변환하기
a_i8 = a.astype(np.int8)
print(a_i8.dtype)

float64
int8


| 속성          | 설명                                                  | 예시 값             |
|---------------|-------------------------------------------------------|---------------------|
| `ndim`        | 배열의 차원 수 (차원 수가 몇 개인지)                  | 1, 2, 3 ...         |
| `shape`       | 배열의 모양(각 차원의 크기를 튜플로 표시)             | (3,), (2, 3), (4, 2, 5) 등 |
| `size`        | 배열에 포함된 전체 원소의 개수                         | 6, 12 등            |
| `dtype`       | 배열 원소의 데이터 타입                                | `int32`, `float64` 등 |
| `itemsize`    | 배열의 각 원소가 차지하는 바이트 수                    | 4, 8 등             |
| `nbytes`      | 배열 전체가 차지하는 메모리 크기 (바이트)             | 24, 48 등           |
| `T`           | 배열의 전치(transpose), 즉 행과 열을 교환한 배열       | 배열 형태에 따라 다름 |
| `data`        | 실제 배열 데이터를 담고 있는 버퍼 (일반적으로 직접 사용하지 않음) | `<memory at 0x...>` |


In [6]:
#코드 6-4
arr = np.array([[0, 1, 2], [3, 4, 5]])

print('type(arr):',type(arr))
print('arr.ndim:',arr.ndim)
print('arr.dtype:',arr.dtype)
print('arr.itemsize:',arr.itemsize)
print('arr.size:',arr.size)
print('arr.nbytes:',arr.nbytes)
print('arr.T:\n',arr.T)
print('arr.shape:',arr.shape)

type(arr): <class 'numpy.ndarray'>
arr.ndim: 2
arr.dtype: int64
arr.itemsize: 8
arr.size: 6
arr.nbytes: 48
arr.T:
 [[0 3]
 [1 4]
 [2 5]]
arr.shape: (2, 3)


### 📌 넘파이 배열 모양을 변경하는 주요 함수/메서드

| 함수/메서드        | 설명                                                                 | 예시 사용법                        |
|--------------------|----------------------------------------------------------------------|------------------------------------|
| `reshape(shape)`   | 배열의 형태를 지정된 `shape`으로 변경 (원소 개수는 같아야 함)        | `a.reshape(2, 3)`                  |
| `flatten()`        | 다차원 배열을 1차원으로 평탄화함 (복사본 반환)                       | `a.flatten()`                      |
| `ravel()`          | 다차원 배열을 1차원으로 평탄화함 (가능하면 원본과 연결된 뷰 반환)    | `a.ravel()`                        |
| `transpose()`      | 배열의 차원 순서를 뒤바꿈 (행렬의 전치 포함)                         | `a.transpose()` 또는 `a.T`         |
| `swapaxes(a1, a2)` | 지정한 두 축의 위치를 바꿈                                            | `a.swapaxes(0, 1)`                 |
| `resize(new_shape)`| 배열을 새로운 크기로 직접 변경 (원본 배열 자체를 수정함)             | `a.resize((3, 2))`                 |
| `expand_dims()`    | 지정한 위치에 새 축(차원)을 추가함                                   | `np.expand_dims(a, axis=0)`       |
| `squeeze()`        | 차원이 1인 축을 제거함                                               | `np.squeeze(a)`                   |


In [ ]:
#코드 6-5
#1차원 배열 생성하기
a = np.arange(8)
print('a\n', a)

#다차원 배열로 변경하기
a.shape = (2,4)
print('shape\n', a)

#1차원 배열로 변경하기
print('flatten\n', a.flatten())

#resize 함수로 모양 변경하기 (원본 배열 자체를 수정함)
a.resize((4,2))
print('resize\n', a)

a
 [0 1 2 3 4 5 6 7]
shape
 [[0 1 2 3]
 [4 5 6 7]]
flatten
 [0 1 2 3 4 5 6 7]
resize
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [ ]:
print("reshape:\n", a.reshape(3, 2))
print("ravel:", a.ravel())
print("transpose:\n", a.transpose())
print("swapaxes:\n", a.swapaxes(0, 1))
print("expand_dims:", np.expand_dims(a, axis=0))  # (1, 2, 3)
print("squeeze:", np.squeeze(np.array([[[1, 2, 3]]])))  # -> [1 2 3]

reshape:
 [[0 1]
 [2 3]
 [4 5]]
flatten: [0 1 2 3 4 5]
ravel: [0 1 2 3 4 5]
transpose:
 [[0 3]
 [1 4]
 [2 5]]
swapaxes:
 [[0 3]
 [1 4]
 [2 5]]
expand_dims: [[[0 1 2]
  [3 4 5]]]
squeeze: [1 2 3]


In [ ]:
a = np.array([[1, 2], [3, 4]])

# flatten: 복사본 생성
f = a.flatten()
f[0] = 100
print("flatten 결과:", f)      # [100   2   3   4]
print("원본 배열 a:", a)        # [[1 2]
                                #  [3 4]]  → 원본 영향 없음

# ravel: 가능한 경우 뷰 반환
r = a.ravel()
r[0] = 200
print("ravel 결과:", r)        # [200   2   3   4]
print("원본 배열 a:", a)        # [[200 2]
                                #  [ 3  4]] → 원본 영향 있음

In [9]:
#코드 6-6
a = np.array([[0, 1, 2], [3, 4, 5]])
print('a\n', a)

b = a.transpose()
print('b\n', b)
c = a.T
print('c\n', c)

a
 [[0 1 2]
 [3 4 5]]
b
 [[0 3]
 [1 4]
 [2 5]]
c
 [[0 3]
 [1 4]
 [2 5]]


In [ ]:
# 확인문제-1
# 0~9까지 정수데이터를 넣은 넘파이 1차원 배열 생성
# 2행 5열로 변형하고 결과를 출력력

a = np.array(range(10), dtype=int)
print("a \n",a)
b = a.reshape(2,5)
print("b \n",b)
c = b.T
print("c \n",c)

a 
 [0 1 2 3 4 5 6 7 8 9]
b 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
c 
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [8]:
# 확인문제-2
# 리스트를 넘파일 배열로 변환하여
# 두 번째 행부터 세 번째 행까지, 첫 번째 열부터 두 번째 열까지 내용을 출력

list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

a = np.array(list)

print(a[1:3,0:3])

[[4 5 6]
 [7 8 9]]


### **2. 배열 원소 조회 및 정렬**

In [ ]:
#코드 6-7
# 마스킹: 조건에 맞는 값을 출력하는 기능능
mask = np.array([0, 1, 1, 0], dtype=bool)
print(mask)

# randn(): 평균이 0, 표준편차가 1인 정규분포를 따르는 난수 생성성
data = np.random.randn(4,2)
print('\ndata 출력\n',data) #랜덤 데이터 배열 data는 책과 다르게 나타남

print('\n마스킹된 데이터 출력\n',data[mask])
print('\n마스킹 역전된 데이터 출력\n',data[~mask])

[False  True  True False]

data 출력
 [[ 0.37505151 -0.79107744]
 [-0.82063619  1.28912088]
 [-0.34448555 -0.88634748]
 [-2.57677751 -0.07705192]]

마스킹된 데이터 출력
 [[-0.82063619  1.28912088]
 [-0.34448555 -0.88634748]]

마스킹 역전된 데이터 출력
 [[ 0.37505151 -0.79107744]
 [-2.57677751 -0.07705192]]


In [10]:
#코드 6-8
posit = data[data > 0]
print('양수 데이터 출력', '\n',posit)

#다중 조건
over1 = data[1][data[1] > 0]
print('두 번째 행의 양수 데이터 출력','\n',over1)

양수 데이터 출력 
 [0.37505151 1.28912088]
두 번째 행의 양수 데이터 출력 
 [1.28912088]


In [ ]:
#코드 6-9
a = np.arange(6)
b = a
print(a)
print(b is a)

# b배열을 바꾸면 a배열도 바뀐다.
b[0] = 10
print(a)

[0 1 2 3 4 5]
True
[10  1  2  3  4  5]


In [ ]:
#코드 6-10
a = np.arange(6)
c = a.copy()

# 주소가 다르다.
c[0] = 20
print('A: ', a)
print('C: ', c)

A:  [0 1 2 3 4 5]
C:  [20  1  2  3  4  5]


In [13]:
#코드 6-11
a = np.array([3, 2, 5, 1, 4])

print('원본\n',a)
print('정렬 후\n',np.sort(a)) # 원본유지

print('원본\n',a)
print('정렬한 인덱스\n',np.argsort(a)) # 정렬된 배열의 원래 인덱스 값

a.sort() # 원본 정렬
print('원본\n',a)

원본
 [3 2 5 1 4]
정렬 후
 [1 2 3 4 5]
원본
 [3 2 5 1 4]
정렬한 인덱스
 [3 1 0 4 2]
원본
 [1 2 3 4 5]


In [15]:
# 확인문제-3
a = np.array([1, 2, 3])
print("a\n", a)
b = np.array([4])
print("b\n", b)
c = a + b
print("c\n", c)

a
 [1 2 3]
b
 [4]
c
 [5 6 7]
